driver:
  gui: false
  forward_agent: yes
  name: vagrant

provisioner:
  name: chef_zero
  #require_chef_omnibus: 11.16.4
  require_chef_omnibus: 12.4.1
  # Obtained from https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2012r2&v=12.2.1
  chef_metadata_url: 'file:///c:/share/chef/metadata/windows_v12.4.1.txt'
  client_rb:
    # Use :enabled, :disabled or :audit_only to run the ServerSpec tests in the recipes
    audit_mode: :enabled
    minimal_ohai: true

transport:
  name: winrm

platforms:
  - name: win
    driver:
      box: "win2012r2-nocm"
      vm_hostname:
      network:
      - ['private_network', {ip: '192.168.56.31'}]
      # Mount local ./chef-kits folder as c:\share on the VM  
      synced_folders:
      - ['./chef-kits', 'c:/share', 'disabled: false']
      customize:
        cpus: 2
        memory: 2048
suites:
  - name: default
    run_list:
       - recipe[myiis-cookbook::default]
       - recipe[myiis-cookbook::app_checkout]
#       - recipe[myiis-cookbook::app_msdeploy_import]
#       - recipe[myiis-cookbook::install_google_chrome]
#       - recipe[myiis-cookbook::audit_recipe]
    attributes:
      git:
        url: file:///c:/share/windows/Git-1.9.5-preview20150319.exe
      myiis-cookbook:
        git-repo: https://github.com/alexpop/myhtml-app
        git-revision: release-2
        doc-root: c:/inetpub/wwwroot
        msdeploy:
          zip: file:///c:/share/windows/all_sites-latest.zip
