Vagrant.configure("2") do |c|
  c.vm.box = "win2012r2"
  c.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_win_chef-provisionerless.box"
  c.vm.network(:private_network, {:ip=>"192.168.56.31"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/apop/gitin/myiis-cookbook/.kitchen/kitchen-vagrant/default-win/share", "/tk-share", disabled: false, create: true
  c.vm.synced_folder "/Users/apop/chef-kits", "c:/share", disabled: false
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--cpus", "2"]
    p.customize ["modifyvm", :id, "--memory", "2048"]
  end
end
